# Generated by Django 4.1.7 on 2023-03-10 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('emp_First_Name', models.CharField(blank=True, max_length=255)),
                ('emp_Last_Name', models.CharField(blank=True, max_length=255)),
                ('emp_Phone_Number', models.CharField(blank=True, max_length=255)),
                ('emp_Email', models.EmailField(blank=True, max_length=255)),
                ('role', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['emp_Last_Name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_First_Name', models.CharField(blank=True, max_length=255)),
                ('customer_Last_Name', models.CharField(blank=True, max_length=255)),
                ('customer_Phone_Number', models.CharField(blank=True, max_length=255)),
                ('customer_Email', models.EmailField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer_Last_Name'],
            },
        ),
    ]
