global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['host.docker.internal:9090']

  - job_name: 'mtail'
    static_configs:
    - targets: ['host.docker.internal:3903'] # mTail logging scrapper

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['host.docker.internal:8083'] # cadvisor container scrapper

  - job_name: 'torchserve'
    static_configs:
    - targets: ['host.docker.internal:8082'] #TorchServe metrics endpoint