{
 "title": "Super Resolution Dashboard",
 "time": { "from": "2023-03-24T09:28:03.000Z", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Total Inference Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ts_inference_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Prediction Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ts_prediction_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ts_inf_CPU_UTILIZATION", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ts_inf_MEMORY_UTILIZATION", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference and Queue Latency",
   "type": "timeseries",
   "description": "Inference and Queue Latency (in microseconds)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "ts_inference_latency_microseconds",
     "legendFormat": "__auto"
    },
    { "expr": "ts_queue_latency_microseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Inference Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ts_inference_latency_microseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Queue Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ts_queue_latency_microseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg GPU Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ts_inf_GPU_UTILIZATION", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg GPU Memory Utililization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ts_inf_GPU_MEMORY_UTILIZATION", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Used / Available",
   "type": "timeseries",
   "description": "RAM Metrics, Memory Used and Memory Available (in MB) and GPU Memory Used (in MB)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "ts_MEMORY_USED", "legendFormat": "__auto" },
    { "expr": "ts_MEMORY_AVAILABLE", "legendFormat": "__auto" },
    { "expr": "ts_GPU_MEMORY_USED", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Utilization",
   "type": "timeseries",
   "description": "CPU, Disk, Memory, and GPU Memory Utilization (%)",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ts_CPU_UTILIZATION", "legendFormat": "__auto" },
    { "expr": "ts_GPU_UTILIZATION", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Used / Available",
   "type": "timeseries",
   "description": "Disk Used and Disk Available metrics (in GB)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "ts_DISK_USAGE", "legendFormat": "__auto" },
    { "expr": "ts_DISK_AVAILABLE", "legendFormat": "__auto" }
   ]
  }
 ]
}