{
 "title": "Torchserve Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Torchserve Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Torchserve Latency\n",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "ts_inference_latency_microseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Inference Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ts_inference_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ts_CPU_UTILIZATION", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ts_MEMORY_UTILIZATION", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ts_DISK_UTILIZATION", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "ts_inf_MEMORY_AVAILABLE", "legendFormat": "__auto" },
    { "expr": "ts_inf_MEMORY_USED", "legendFormat": "__auto" },
    { "expr": "ts_inf_GPU_MEMORY_USED", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ts_GPU_UTILIZATION", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Memory Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ts_GPU_MEMORY_UTILIZATION", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "targets": [
    { "expr": "ts_DISK_AVAILABLE", "legendFormat": "__auto" },
    { "expr": "ts_DISK_USAGE", "legendFormat": "__auto" }
   ]
  }
 ]
}